
Theoretical Questions


1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
enhance Python's capabilities for numerical operations?

Ans= NumPy (Numerical Python) is a powerful library in Python that provides support for scientific computing and data analysis. 
It significantly enhances Python's capabilities for numerical operations by offering a variety of functionalities that are efficient, optimized,
and easy to use.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other?

Ans=np.mean() is simpler and calculates the arithmetic mean with equal weights.
np.average() can compute both the arithmetic mean and a weighted average when weights are provided.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
arrays

Ans=To reverse elements, slicing with [::-1] can be used.
This works for both 1D and 2D arrays.

In [1]:
import numpy as np
#1D array
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
#2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Reverse rows
reversed_rows = arr[::-1]

# Reverse columns
reversed_columns = arr[:, ::-1]

print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
in memory management and performance.

Ans= In NumPy, the data type (or dtype) of elements in an array can be determined using the dtype attribute.
Memory Management:

NumPy allows you to specify the data type of an array at the time of creation, optimizing memory usage.
For example, an array of int32 takes up less memory compared to int64

Performance:

NumPy operations are highly optimized for specific data types, ensuring faster computations.
Using a smaller data type (e.g., int8 instead of int64) can improve performance when working with large datasets, provided the smaller type fits the data range.


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans= An ndarray (N-dimensional array) in NumPy is a powerful, multi-dimensional, fixed-size array object designed
for efficient numerical computation. It is the core data structure in NumPy.

NumPy ndarray	
Elements must have the same data type.	
Faster due to vectorized operations and C backend.	
More memory-efficient (contiguous memory).	
Supports element-wise operations directly.	
Native support for multidimensional arrays.	
Offers rich functionality for numerical tasks.
Supports advanced indexing (e.g., slicing, masks).	


Python List
        
Can store elements of different types.
Slower as it uses high-level loops.
Less efficient (pointers to objects).
Requires loops for such operations.
Requires nested lists for dimensions.
Lacks built-in numerical capabilities.
Limited to basic indexing.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

Ans=NumPy arrays significantly outperform Python lists in large-scale numerical operations due to their optimized design and implementation.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
output

Ans= Both vstack() and hstack() are functions used to combine arrays, but they differ in how they perform the stacking
vstack()
Stacks vertically (row-wise).
Same number of columns.
Adds to the number of rows.

hstack()
Stacks horizontally (column-wise).
Same number of rows.
Adds to the number of columns.

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
array dimensions.

Ans=fliplr() (Flip Left to Right)
Reverses the order of columns in a 2D array (horizontal flipping).
Applicable only to arrays with 2 or more dimensions.
The array is flipped along the second axis (columns).

flipud() (Flip Up to Down):
Reverses the order of rows in a 2D array (vertical flipping).
Applicable to arrays of any dimension.
The array is flipped along the first axis (rows).

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans=Functionality of array_split() in NumPy The numpy.array_split() method splits an array into multiple sub-arrays along a specified axis.
It is similar to split(), but it is more flexible as it can handle uneven splits.

Unlike split(), which raises an error for uneven splits, array_split() handles them gracefully.
If the array size is not evenly divisible by the number of splits, some sub-arrays will have fewer elements.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
operations?

Ans= Vectorization refers to the process of applying operations directly on entire arrays, avoiding explicit loops in Python. NumPy achieves 
this by performing operations at the C or Fortran level, which is much faster than Python's interpreted loops.

Broadcasting
Broadcasting is a method that allows NumPy to perform operations on arrays of different shapes. 
It automatically expands the smaller array to match the shape of the larger one without explicitly copying the data

They Contribute to Efficiency:
Vectorization:

Speeds up computation by performing operations at the underlying C level.
Avoids Python's slow loops, leading to significant performance gains for large arrays.
Broadcasting:

Minimizes memory usage by avoiding explicit data replication.
Simplifies code by enabling operations on arrays with different shapes.



Practical Questions



1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

In [2]:
import numpy as np

In [21]:
A=np.random.randint(1,100,(3,3))

In [22]:
B=A.T

In [23]:
A

array([[60, 61, 74],
       [75,  2, 67],
       [52, 15, 34]])

In [24]:
B

array([[60, 75, 52],
       [61,  2, 15],
       [74, 67, 34]])

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [28]:
a=np.arange(10)

In [29]:
_a=a.reshape(2,5)

In [30]:
_A=_a.reshape(5,2)

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [34]:
a=np.random.rand(4,4)

In [35]:
border=np.pad(a,pad_width=1,mode='constant',constant_values=0)

In [36]:
border

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.30872237, 0.0775789 , 0.95656704, 0.13258254,
        0.        ],
       [0.        , 0.59012482, 0.66955377, 0.4940176 , 0.06710874,
        0.        ],
       [0.        , 0.85086652, 0.81720331, 0.70899495, 0.70241167,
        0.        ],
       [0.        , 0.14014165, 0.0185987 , 0.72768145, 0.58753726,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [37]:
a=np.arange(10,60,5)

In [38]:
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element.

In [39]:
text=np.array(['python','numpy','pandas'])
text

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [42]:
upr=np.char.upper(text)
lwr=np.char.lower(text)
tle=np.char.title(text)

6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [45]:
aa=np.array(['hello','smit','fine'])

In [46]:
sp=np.char.join(' ',aa)
sp

array(['h e l l o', 's m i t', 'f i n e'], dtype='<U9')

In [ ]:
7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [49]:
a=np.array([[1,2,3],
          [4,5,6]])
b=np.array([[7,8,9],
            [1,3,4]])

In [52]:
c=a-b
d=a*b
e=a+b
f=a/b

In [ ]:
8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [57]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [58]:
daigonal=np.diag(a)
daigonal

array([1., 1., 1., 1., 1.])

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.

In [59]:
aa=np.random.randint(0,1001,100)
aa

array([541, 281, 756, 283, 377, 879, 135, 612, 658, 438, 120, 811, 581,
       742, 663, 568, 263, 731,  14, 630, 849, 911, 149, 150, 923,  30,
       181, 679, 217, 723, 861, 468, 563, 735, 866, 492, 459, 511, 857,
       732, 157, 839, 170, 762, 280, 359, 995, 443, 791, 333,  97, 996,
       734, 440, 829, 853, 647, 631, 977, 635, 779,  12, 336, 153, 404,
       386, 499, 289, 318, 384, 443, 297, 871, 899, 524, 984, 849, 550,
       585, 450, 885, 654, 136, 391, 654, 309, 954, 321, 903, 675, 719,
       173,  48, 961, 426, 895, 344,  66, 140, 794])

In [60]:
def prime(p):
    if p<2:
        return False
    for i in range(2,int(np.sqrt(p))+1):
        if p%i==0:
            return False
    return True

In [62]:
x=np.array([P for P in aa if prime(P)])
x

array([541, 281, 283, 811, 263, 911, 149, 181, 563, 857, 157, 839, 359,
       443,  97, 829, 853, 647, 631, 977, 499, 443, 719, 173])

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages

In [70]:
w=np.random.randint(10,40,28)
ww=w.reshape(4,7)
W=np.mean(ww,axis=1)
W

array([22.42857143, 24.28571429, 23.85714286, 29.71428571])